import {xml,markdown} from './format.mjs';

export function renderReadme(data,config,assets={desktop:'assets/profile.svg',mobile:'assets/profile-mobile.svg',still:'assets/profile-still.svg',mobileStill:'assets/profile-mobile-still.svg'}){
  const s=data.spotlight,query=encodeURIComponent(`author:${config.username} is:pr is:merged is:public -user:${config.username}`);
  const projects=data.projects.slice(0,config.projects.maxVisible);
  const allLabel=data.projects.length>projects.length?`All ${data.projects.length} projects`:'All projects';
  const links=[...(s?[`[PR #${s.number}](${s.url})`]:[]),...projects.map(p=>`[${markdown(p.name)}](${p.url})`),`[${allLabel}](https://github.com/${config.username}?tab=repositories)`,`[Merged contributions](https://github.com/search?q=${query}&type=pullrequests)`];
  return `<!-- Generated by scripts/update-profile.mjs. Edit profile.config.json for content. -->
<picture>
  <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="${assets.mobileStill}">
  <source media="(prefers-reduced-motion: reduce)" srcset="${assets.still}">
  <source media="(max-width: 600px)" srcset="${assets.mobile}">
  <img src="${assets.desktop}" width="100%" alt="${xml(config.name)} — AI engineering, ${data.mergedPullRequests} merged upstream PRs, projects and contribution impact">
</picture>

${links.join(' · ')}

${Object.entries(config.links).map(([label,url])=>`[${markdown(label)}](${url})`).join(' · ')}
`;
}
