import {xml} from './format.mjs';
import {buildModules} from './modules.mjs';

function image(module,assets){
  const paths=assets[module.id]||{
    desktop:'assets/generated/'+module.id+'.svg',
    mobile:'assets/generated/'+module.id+'-mobile.svg',
    still:'assets/generated/'+module.id+'-still.svg',
    mobileStill:'assets/generated/'+module.id+'-mobile-still.svg'
  };
  const picture='<picture><source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="'+xml(paths.mobileStill)+'"><source media="(prefers-reduced-motion: reduce)" srcset="'+xml(paths.still)+'"><source media="(max-width: 600px)" srcset="'+xml(paths.mobile)+'"><img src="'+xml(paths.desktop)+'" width="100%" alt="'+xml(module.alt)+'"></picture>';
  return '<a href="'+xml(module.href)+'">'+picture+'</a>';
}

export function renderReadme(data,config,assets={}){
  const modules=buildModules(data,config);
  const dashboard=modules.map(module=>'<p>'+image(module,assets)+'</p>').join('\n\n');
  const contacts=Object.entries(config.links||{}).map(([label,url])=>'<a href="'+xml(url)+'">'+xml(label)+'</a>').join(' · ');
  return '<!-- Generated by scripts/update-profile.mjs. Edit profile.config.json for content. -->\n'+dashboard+(contacts?'\n\n<p>'+contacts+'</p>':'')+'\n';
}
