import {xml,markdown} from './format.mjs';
import {buildPresentation} from './modules.mjs';

export function renderReadme(data,config,assets={}){
  const blocks=buildPresentation(data,config).map(block=>{
    if(block.kind==='repositories')return `<details>\n<summary>Other public repositories (${block.items.length})</summary>\n\n${block.items.map(project=>`- [${markdown(project.name)}](${project.url})`).join('\n')}\n\n</details>`;
    const paths=assets[block.id]||{desktop:`assets/generated/${block.id}.svg`,mobile:`assets/generated/${block.id}-mobile.svg`,still:`assets/generated/${block.id}-still.svg`,mobileStill:`assets/generated/${block.id}-mobile-still.svg`};
    const picture=`<picture>\n  <source media="(prefers-reduced-motion: reduce) and (max-width: 600px)" srcset="${paths.mobileStill}">\n  <source media="(prefers-reduced-motion: reduce)" srcset="${paths.still}">\n  <source media="(max-width: 600px)" srcset="${paths.mobile}">\n  <img src="${paths.desktop}" width="100%" alt="${xml(block.alt)}">\n</picture>`;
    return `<p>\n${block.href?`<a href="${xml(block.href)}">\n${picture}\n</a>`:picture}\n</p>`;
  });
  return `<!-- Generated by scripts/update-profile.mjs. Edit profile.config.json for content. -->\n${blocks.join('\n\n')}\n\n${Object.entries(config.links).map(([label,url])=>`[${markdown(label)}](${url})`).join(' · ')}\n`;
}
